apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ams-app
  name: ams-app
spec:
  type: LoadBalancer
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    io.kompose.service: ams-app