apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ams-local
  name: ams-local
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ams-local
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ams-local
    spec:
      containers:
      - image: ams:h2-db
        imagePullPolicy: IfNotPresent
        name: ams
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-28T19:11:47Z"
  labels:
    app: ams-local
  name: ams-local
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.85.30
  clusterIPs:
  - 10.103.85.30
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ams-local
  sessionAffinity: None
  type: LoadBalancer