version: '3.1'
services:
  app:
    container_name: ams-app
    restart: always
    image: kharvinagaraj1/ams:0.1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - db
    environment:
      DOCKER_HOSTNAME: postgresdb
  db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=ams
    volumes:
      - postgresql-db-data-volume:/var/lib/postgresql
volumes:
  postgresql-db-data-volume: