apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: ams
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          image: postgres:latest
          #args:
            #- "--ignore-db-dir=lost+found"
          name: postgresdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-db-data-volume
      restartPolicy: Always
      volumes:
        - name: postgresql-db-data-volume
          persistentVolumeClaim:
            claimName: postgresql-db-data-volume