apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-05-28T19:11:27Z"
  generation: 4
  labels:
    app: ams-local
  name: ams-local
  namespace: default
  resourceVersion: "20166"
  uid: e18b89f4-4706-40a2-9658-0002fb9e52fe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ams-local
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ams-local
    spec:
      containers:
      - image: ams:h2-db
        imagePullPolicy: IfNotPresent
        name: ams
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-05-28T19:11:27Z"
    lastUpdateTime: "2022-05-28T19:11:29Z"
    message: ReplicaSet "ams-local-5d9df47c9d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-29T11:53:45Z"
    lastUpdateTime: "2022-05-29T11:53:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
